[package]
name = "parliamentbomb"
version = "0.1.0"
authors = [ "gradetools contributors", "parliamentbomb contributors" ]
edition = "2021"

[dependencies]
serenity = { version = "0.10.9", features = ["voice"] }
dotenv = "0.15.0"
tokio = { version = "1.0", features = ["full"] }
