name: "Build ParliamentBomb on Cargo (ubuntu)"

on:
  push:

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        override: true

    - name: Build
      uses: dtolnay/rust-toolchain@stable
      with:
        command: build

    - name: Run tests
      uses: dtolnay/rust-toolchain@stable
      with:
        command: test
