name: "Build ParliamentBomb on Nix (ubuntu)"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - name: Building package
        run: nix build --extra-experimental-features nix-command --extra-experimental-features flakes 
